version: '3.8'

services:
  # Backend service (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: investsim-backend
    restart: unless-stopped
    ports:
      - "5098:5098"
    environment:
      - NODE_ENV=production
      - PORT=5098
      - HOST=0.0.0.0
    volumes:
      # Mount data directory for file-based storage
      - ./backend/data:/app/data:ro
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        
    networks:
      - investsim-network

  # Frontend service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://backend:3000
    container_name: investsim-frontend
    restart: unless-stopped
    ports:
      - "5099:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://backend:3000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - investsim-network

networks:
  investsim-network:
    driver: bridge
